version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: oap_postgres
    environment:
      POSTGRES_USER: oap_user
      POSTGRES_PASSWORD: oap_password
      POSTGRES_DB: oap_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U oap_user -d oap_db"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:7-alpine
    container_name: oap_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: